/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author sapat
 */
public class MainMenu_GUI extends javax.swing.JFrame {

    /**
     * Creates new form SetUp_GUI
     */
    public MainMenu_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MainMenuBG_lbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        referees_btn = new javax.swing.JMenu();
        addReferee_btn = new javax.swing.JMenuItem();
        ReadUpdateDeleteReferee_btn = new javax.swing.JMenuItem();
        matches_btn = new javax.swing.JMenu();
        addMatch_btn = new javax.swing.JMenuItem();
        ReadUpdateDeleteMatch_btn = new javax.swing.JMenuItem();
        logout_btn = new javax.swing.JMenu();
        exit_btn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        MainMenuBG_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/MainMenu.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuBG_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainMenuBG_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        referees_btn.setText("Arbitros");

        addReferee_btn.setText("Cadstrar");
        referees_btn.add(addReferee_btn);

        ReadUpdateDeleteReferee_btn.setText("Consultar/Alterar/Excluir");
        referees_btn.add(ReadUpdateDeleteReferee_btn);

        jMenuBar1.add(referees_btn);

        matches_btn.setText("Partidas");

        addMatch_btn.setText("Adicionar");
        matches_btn.add(addMatch_btn);

        ReadUpdateDeleteMatch_btn.setText("Condultar/Alterar/Excluir");
        matches_btn.add(ReadUpdateDeleteMatch_btn);

        jMenuBar1.add(matches_btn);

        logout_btn.setText("Logout");
        jMenuBar1.add(logout_btn);

        exit_btn.setText("Sair");
        jMenuBar1.add(exit_btn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainMenuBG_lbl;
    private javax.swing.JMenuItem ReadUpdateDeleteMatch_btn;
    private javax.swing.JMenuItem ReadUpdateDeleteReferee_btn;
    private javax.swing.JMenuItem addMatch_btn;
    private javax.swing.JMenuItem addReferee_btn;
    private javax.swing.JMenu exit_btn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu logout_btn;
    private javax.swing.JMenu matches_btn;
    private javax.swing.JMenu referees_btn;
    // End of variables declaration//GEN-END:variables
}
