/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sapat
 */
public class NewReferee_GUI extends javax.swing.JFrame {

    /**
     * Creates new form SetUp_GUI
     */
    public NewReferee_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cpf_txt = new javax.swing.JTextField();
        totalGamesOfficiated_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        add_btn = new javax.swing.JButton();
        NewRefereeBG_lbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mainMenuMenu_btn = new javax.swing.JMenu();
        mainMenu_btn = new javax.swing.JMenuItem();
        toolsMenu_btn = new javax.swing.JMenu();
        notePad_btn = new javax.swing.JMenuItem();
        referees_btn = new javax.swing.JMenu();
        addReferee_btn = new javax.swing.JMenuItem();
        ReadUpdateDeleteReferee_btn = new javax.swing.JMenuItem();
        matches_btn = new javax.swing.JMenu();
        addMatch_btn = new javax.swing.JMenuItem();
        ReadUpdateDeleteMatch_btn = new javax.swing.JMenuItem();
        logoutMenu_btn = new javax.swing.JMenu();
        logout_btn = new javax.swing.JMenuItem();
        exitMenu_btn = new javax.swing.JMenu();
        exit_btn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        cpf_txt.setText("CPF");
        jPanel1.add(cpf_txt);
        cpf_txt.setBounds(170, 100, 280, 30);

        totalGamesOfficiated_txt.setText("Total De Partidas Apitadas");
        jPanel1.add(totalGamesOfficiated_txt);
        totalGamesOfficiated_txt.setBounds(170, 200, 280, 30);

        name_txt.setText("Nome");
        jPanel1.add(name_txt);
        name_txt.setBounds(170, 150, 280, 30);

        add_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add_btn.setText("ADICIONAR");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        jPanel1.add(add_btn);
        add_btn.setBounds(170, 250, 280, 30);

        NewRefereeBG_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AddNewReferee.png"))); // NOI18N
        jPanel1.add(NewRefereeBG_lbl);
        NewRefereeBG_lbl.setBounds(0, 0, 500, 480);

        mainMenuMenu_btn.setText("Menu");

        mainMenu_btn.setText("Voltar ao Menu Principal");
        mainMenu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenu_btnActionPerformed(evt);
            }
        });
        mainMenuMenu_btn.add(mainMenu_btn);

        jMenuBar1.add(mainMenuMenu_btn);

        toolsMenu_btn.setText("Ferramentas");

        notePad_btn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        notePad_btn.setText("Bloco de notas");
        notePad_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notePad_btnActionPerformed(evt);
            }
        });
        toolsMenu_btn.add(notePad_btn);

        jMenuBar1.add(toolsMenu_btn);

        referees_btn.setText("Arbitros");

        addReferee_btn.setText("Cadstrar");
        addReferee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addReferee_btnActionPerformed(evt);
            }
        });
        referees_btn.add(addReferee_btn);

        ReadUpdateDeleteReferee_btn.setText("Consultar/Alterar/Excluir");
        ReadUpdateDeleteReferee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadUpdateDeleteReferee_btnActionPerformed(evt);
            }
        });
        referees_btn.add(ReadUpdateDeleteReferee_btn);

        jMenuBar1.add(referees_btn);

        matches_btn.setText("Partidas");

        addMatch_btn.setText("Adicionar Nova Partida");
        addMatch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMatch_btnActionPerformed(evt);
            }
        });
        matches_btn.add(addMatch_btn);

        ReadUpdateDeleteMatch_btn.setText("Consultar/Alterar/Excluir");
        ReadUpdateDeleteMatch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadUpdateDeleteMatch_btnActionPerformed(evt);
            }
        });
        matches_btn.add(ReadUpdateDeleteMatch_btn);

        jMenuBar1.add(matches_btn);

        logoutMenu_btn.setText("Logout");
        logoutMenu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenu_btnActionPerformed(evt);
            }
        });

        logout_btn.setText("Realizar Logout");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        logoutMenu_btn.add(logout_btn);

        jMenuBar1.add(logoutMenu_btn);

        exitMenu_btn.setText("Sair");
        exitMenu_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenu_btnActionPerformed(evt);
            }
        });

        exit_btn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        exit_btn.setText("Fechar");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        exitMenu_btn.add(exit_btn);

        jMenuBar1.add(exitMenu_btn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(500, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mainMenu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenu_btnActionPerformed
        Model.Funcs_DAO.changeScreen(this, new MainMenu_GUI());
    }//GEN-LAST:event_mainMenu_btnActionPerformed

    private void notePad_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notePad_btnActionPerformed
        try {
            Runtime.getRuntime().exec("cmd.exe /c start notepad.exe");
        } catch (IOException ex) {
            Logger.getLogger(MainMenu_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_notePad_btnActionPerformed

    private void addReferee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addReferee_btnActionPerformed

    }//GEN-LAST:event_addReferee_btnActionPerformed

    private void ReadUpdateDeleteReferee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadUpdateDeleteReferee_btnActionPerformed
        Model.Funcs_DAO.changeScreen(this, new ReadUpdateDeleteReferee_GUI());
    }//GEN-LAST:event_ReadUpdateDeleteReferee_btnActionPerformed

    private void addMatch_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMatch_btnActionPerformed
        Model.Funcs_DAO.changeScreen(this, new NewMatch_GUI());
    }//GEN-LAST:event_addMatch_btnActionPerformed

    private void ReadUpdateDeleteMatch_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadUpdateDeleteMatch_btnActionPerformed
        Model.Funcs_DAO.changeScreen(this, new ReadUpdateDeleteMatch_GUI());
    }//GEN-LAST:event_ReadUpdateDeleteMatch_btnActionPerformed

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        if (main.Main.manager.logout()) {
            JOptionPane.showMessageDialog(null, "LOGOUT REALIZADO COM SUCESSO!");
            Model.Funcs_DAO.changeScreen(this, new SetUp_GUI());
        } else {
            JOptionPane.showMessageDialog(null, "IMPOSSIVEL FAZER O LOGOUT!");
        }
    }//GEN-LAST:event_logout_btnActionPerformed

    private void logoutMenu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenu_btnActionPerformed

    }//GEN-LAST:event_logoutMenu_btnActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btnActionPerformed

    private void exitMenu_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenu_btnActionPerformed

    }//GEN-LAST:event_exitMenu_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        try {
            String totalGamesResponse = totalGamesOfficiated_txt.getText();
            int totalGamesOfficiated = Integer.parseInt(totalGamesResponse);
            if (main.Main.refereeManager.addNewReferee(cpf_txt.getText(), name_txt.getText(), totalGamesOfficiated)){
                JOptionPane.showMessageDialog(null, "ARBITRO ADICIONADO COM SUCESSO AO SISTEMA!");
                Model.Funcs_DAO.changeScreen(this, new MainMenu_GUI());
            } else {
                JOptionPane.showMessageDialog(null, "ARBITRO NAO CADASTRADO!\nCPF ja cadastrado!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERRO AO ADICIONAR ARBITRO!\nOcorreu um erro ao adicionar arbitro. \nCodigo do erro: " + e);
        }
    }//GEN-LAST:event_add_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewReferee_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewReferee_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewReferee_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewReferee_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewReferee_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NewRefereeBG_lbl;
    private javax.swing.JMenuItem ReadUpdateDeleteMatch_btn;
    private javax.swing.JMenuItem ReadUpdateDeleteReferee_btn;
    private javax.swing.JMenuItem addMatch_btn;
    private javax.swing.JMenuItem addReferee_btn;
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField cpf_txt;
    private javax.swing.JMenu exitMenu_btn;
    private javax.swing.JMenuItem exit_btn;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu logoutMenu_btn;
    private javax.swing.JMenuItem logout_btn;
    private javax.swing.JMenu mainMenuMenu_btn;
    private javax.swing.JMenuItem mainMenu_btn;
    private javax.swing.JMenu matches_btn;
    private javax.swing.JTextField name_txt;
    private javax.swing.JMenuItem notePad_btn;
    private javax.swing.JMenu referees_btn;
    private javax.swing.JMenu toolsMenu_btn;
    private javax.swing.JTextField totalGamesOfficiated_txt;
    // End of variables declaration//GEN-END:variables
}
